import { readFileSync, existsSync } from 'fs';
import type { GroupedVars } from '../types.js';

/**
 * Parse an existing .env.example and return declared var names.
 */
export function parseEnvExample(filePath: string): Set<string> {
  if (!existsSync(filePath)) return new Set();

  const vars = new Set<string>();

  for (const line of readFileSync(filePath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;

    const key = trimmed.slice(0, eqIndex).trim();
    if (key) vars.add(key);
  }

  return vars;
}

interface CategoryRule {
  pattern: RegExp;
  label: string;
}

const CATEGORY_RULES: CategoryRule[] = [
  { pattern: /^(DB_|DATABASE_|MONGO|POSTGRES|MYSQL|REDIS|SQLITE|SUPABASE_DB)/i, label: 'Database'            },
  { pattern: /^(JWT_|AUTH_|SESSION_|SECRET|PASSWORD|PASS_|BCRYPT)/i,            label: 'Auth & Security'     },
  { pattern: /^(AWS_|S3_|GCS_|AZURE_|CLOUDFLARE_|SUPABASE_)/i,                 label: 'Cloud & Storage'     },
  { pattern: /^(SMTP_|MAIL_|EMAIL_|SENDGRID_|MAILGUN_|RESEND_)/i,              label: 'Email'               },
  { pattern: /^(STRIPE_|PAYPAL_|PAYMENT_|LEMON_)/i,                             label: 'Payments'            },
  { pattern: /^(OPENAI_|ANTHROPIC_|GEMINI_|HUGGING|COHERE_|REPLICATE_)/i,      label: 'AI / LLM'            },
  { pattern: /^(NEXT_PUBLIC_|VITE_|REACT_APP_|PUBLIC_)/i,                       label: 'Frontend / Public'   },
  { pattern: /^(PORT|HOST|BASE_URL|API_URL|APP_URL|CORS|ORIGIN)/i,             label: 'Server'              },
  { pattern: /^(GOOGLE_|GITHUB_|FACEBOOK_|TWITTER_|DISCORD_|OAUTH_)/i,         label: 'OAuth'               },
  { pattern: /^(SENTRY_|DATADOG_|LOG_|LOGGING_|LOGTAIL_|AXIOM_)/i,            label: 'Monitoring & Logging' },
];

/**
 * Group env var names into labelled categories.
 */
export function groupByCategory(varNames: string[]): GroupedVars {
  const groups: GroupedVars = new Map();
  const uncategorized: string[] = [];

  for (const name of varNames) {
    let matched = false;
    for (const { pattern, label } of CATEGORY_RULES) {
      if (pattern.test(name)) {
        if (!groups.has(label)) groups.set(label, []);
        groups.get(label)!.push(name);
        matched = true;
        break;
      }
    }
    if (!matched) uncategorized.push(name);
  }

  if (uncategorized.length > 0) groups.set('General', uncategorized);
  return groups;
}

/**
 * Render grouped vars into a formatted .env.example string.
 */
export function renderEnvExample(groups: GroupedVars): string {
  const lines: string[] = [
    '# Generated by arven — https://github.com/yourusername/arven',
    '# arven (Welsh: "to oversee / to keep watch") watches over your env vars.',
    '# Edit values below before running the project.',
    '',
  ];

  for (const [category, vars] of groups) {
    lines.push(`# ${category}`);
    for (const v of [...vars].sort()) lines.push(`${v}=`);
    lines.push('');
  }

  return lines.join('\n');
}
