import { DocsLayout } from "../../components/docs/docs-layout";
import { DocsCodeBlock, DocsSection } from "../../components/docs/docs-primitives";
import type { DocsSlug } from "../../components/docs/docs-nav";

const toc = [
  { label: "Setup", href: "#setup" },
  { label: "Generated File", href: "#generated-file" },
];

export function GettingStartedPage() {
  const activeSlug: DocsSlug = "getting-started";

  return (
    <DocsLayout activeSlug={activeSlug} toc={toc}>
      <div className="space-y-12">
        <header className="space-y-3">
          <p className="text-sm text-zinc-400">Getting Started</p>
          <h1 className="text-2xl font-normal tracking-[-0.04em] text-zinc-900 sm:text-3xl">
            Start guarding commits
          </h1>
        </header>

        <DocsSection id="setup" title="Setup">
          <p>Run once inside any git project:</p>
          <DocsCodeBlock>{`arven init`}</DocsCodeBlock>
          <p>arven will:</p>
          <ol className="space-y-3 pl-6">
            <li>
              Install a pre-commit hook at{" "}
              <code className="rounded bg-zinc-100 px-1.5 py-0.5">.git/hooks/pre-commit</code>
            </li>
            <li>Scan your entire codebase for env var usage</li>
            <li>
              Generate a grouped{" "}
              <code className="rounded bg-zinc-100 px-1.5 py-0.5">.env.example</code>
            </li>
          </ol>
        </DocsSection>

        <DocsSection id="generated-file" title="What gets generated">
          <DocsCodeBlock>{`# Generated by arven
# arven (Welsh: "to oversee / to keep watch")

# Auth & Security
JWT_SECRET=
SESSION_SECRET=

# Database
DATABASE_URL=
REDIS_URL=

# Payments
STRIPE_SECRET_KEY=

# Server
BASE_URL=
PORT=`}</DocsCodeBlock>
        </DocsSection>
      </div>
    </DocsLayout>
  );
}
